### ISSUE TITLE
Player memory leak

### ISSUE THREAD

**Issue by ChanceSD** [Revivalo/PlayerWarps#1]
There's a player memory leak in this class https://github.com/Revivalo/PlayerWarps/blob/main/src/main/java/dev/revivalo/playerwarps/user/UserHandler.java on the USERS map.
Since the User class has a Player instance it should be removed when the player logs out, otherwise the memory usage will keep increasing as more players enter and leave the server.

So the easy solution I suggest is just adding a PlayerQuitEvent listener and remove the player from the USERS map on quit. Should be enough to solve it.

**Comment by Revivalo** [comment]
Good point, will tweak that in following patch.
